services:
  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: printanista
      MYSQL_USER: printanista
      MYSQL_PASSWORD: printanista123
    ports: ["3307:3306"]
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on: [db]
    ports: ["8000:8000"]
