services:
 db:
  image: mariadb:11
  environment:
   MYSQL_ROOT_PASSWORD: root123
   MYSQL_DATABASE: printanista
   MYSQL_USER: printanista
   MYSQL_PASSWORD: printanista123
  volumes:
   - ./db/full_dump.sql:/docker-entrypoint-initdb.d/init.sql

 app:
  build: .
  ports:
   - "8000:8000"
  depends_on:
   - db
